# Generated by Django 4.2.1 on 2023-05-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('quantity', models.IntegerField(default=1)),
                ('businessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.business')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('visitHistory', models.JSONField(blank=True, default=list, max_length=5)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.account')),
            ],
        ),
    ]
