# Generated by Django 4.2.1 on 2023-05-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='shopping.account'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('products', models.JSONField(default=list)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.account')),
                ('businessID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.business')),
            ],
        ),
    ]
